# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWUEOs14dhEuyf5ScNlzl_uLpO6lguSa
"""

print ("version 2.0")